# ruff: An extremely fast Python linter, written in Rust.

# If ${config_dir}/ruff/pyproject.toml exists, then that file will be
# used instead of the default configuration.

[tool.ruff]
select = ["ALL"]
ignore = [
    "ANN101",  # missing-type-self; nobody gives a type annotation for "self"
    "D202",    # no-blank-line-after-function: I prefer one line
    "D203",    # one-blank-line-before-class: incompatible with no-blank-line-before-class
    "D212",    # multi-line-summary-first-line: fails for multi-line comments
    "ERA001",  # commented-out-code; false positives
    "T20",     # (p-)?print-found; print is an ok function to use
]